name: Next.js CI with pnpm (Windows)

on: [push, pull_request]

jobs:
    build-test:
        runs-on: windows-latest

        env:
            NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Lint code
              run: pnpm run lint

            - name: Format check
              run: pnpm exec prettier --check "src/**/*.{ts,tsx,js,jsx,json,scss,css,md}" "package.json" "tsconfig.json" ".github/workflows/**/*.yml"

            - name: Build Next.js app
              run: pnpm run build

            - name: Run tests
              run: pnpm run test
